#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Muhasebe.Fonksiyonlar
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Sirket-Muhasebe")]
	public partial class DatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCARIGRUPLARI(CARIGRUPLARI instance);
    partial void UpdateCARIGRUPLARI(CARIGRUPLARI instance);
    partial void DeleteCARIGRUPLARI(CARIGRUPLARI instance);
    partial void InsertCARILER(CARILER instance);
    partial void UpdateCARILER(CARILER instance);
    partial void DeleteCARILER(CARILER instance);
    partial void InsertSTOKGRUPLARI(STOKGRUPLARI instance);
    partial void UpdateSTOKGRUPLARI(STOKGRUPLARI instance);
    partial void DeleteSTOKGRUPLARI(STOKGRUPLARI instance);
    partial void InsertSTOKLAR(STOKLAR instance);
    partial void UpdateSTOKLAR(STOKLAR instance);
    partial void DeleteSTOKLAR(STOKLAR instance);
    partial void InsertKASAHAREKETLERI(KASAHAREKETLERI instance);
    partial void UpdateKASAHAREKETLERI(KASAHAREKETLERI instance);
    partial void DeleteKASAHAREKETLERI(KASAHAREKETLERI instance);
    partial void InsertKASALAR(KASALAR instance);
    partial void UpdateKASALAR(KASALAR instance);
    partial void DeleteKASALAR(KASALAR instance);
    partial void InsertCARIHAREKETLERI(CARIHAREKETLERI instance);
    partial void UpdateCARIHAREKETLERI(CARIHAREKETLERI instance);
    partial void DeleteCARIHAREKETLERI(CARIHAREKETLERI instance);
    #endregion
		
		public DatabaseDataContext() : 
				base(global::Muhasebe.Properties.Settings.Default.Sirket_MuhasebeConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CARIGRUPLARI> CARIGRUPLARIs
		{
			get
			{
				return this.GetTable<CARIGRUPLARI>();
			}
		}
		
		public System.Data.Linq.Table<CARILER> CARILERs
		{
			get
			{
				return this.GetTable<CARILER>();
			}
		}
		
		public System.Data.Linq.Table<STOKGRUPLARI> STOKGRUPLARIs
		{
			get
			{
				return this.GetTable<STOKGRUPLARI>();
			}
		}
		
		public System.Data.Linq.Table<STOKLAR> STOKLARs
		{
			get
			{
				return this.GetTable<STOKLAR>();
			}
		}
		
		public System.Data.Linq.Table<KASAHAREKETLERI> KASAHAREKETLERIs
		{
			get
			{
				return this.GetTable<KASAHAREKETLERI>();
			}
		}
		
		public System.Data.Linq.Table<KASALAR> KASALARs
		{
			get
			{
				return this.GetTable<KASALAR>();
			}
		}
		
		public System.Data.Linq.Table<CARIHAREKETLERI> CARIHAREKETLERIs
		{
			get
			{
				return this.GetTable<CARIHAREKETLERI>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CARIGRUPLARI")]
	public partial class CARIGRUPLARI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cariID;
		
		private string _cariGrupAdi;
		
		private string _cariGrupKodu;
		
		private System.Nullable<System.DateTime> _cariSaveDate;
		
		private System.Nullable<int> _cariSaveUser;
		
		private System.Nullable<System.DateTime> _cariEditDate;
		
		private System.Nullable<int> _cariEditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OncariIDChanging(int value);
    partial void OncariIDChanged();
    partial void OncariGrupAdiChanging(string value);
    partial void OncariGrupAdiChanged();
    partial void OncariGrupKoduChanging(string value);
    partial void OncariGrupKoduChanged();
    partial void OncariSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OncariSaveDateChanged();
    partial void OncariSaveUserChanging(System.Nullable<int> value);
    partial void OncariSaveUserChanged();
    partial void OncariEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OncariEditDateChanged();
    partial void OncariEditUserChanging(System.Nullable<int> value);
    partial void OncariEditUserChanged();
    #endregion
		
		public CARIGRUPLARI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cariID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cariID
		{
			get
			{
				return this._cariID;
			}
			set
			{
				if ((this._cariID != value))
				{
					this.OncariIDChanging(value);
					this.SendPropertyChanging();
					this._cariID = value;
					this.SendPropertyChanged("cariID");
					this.OncariIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cariGrupAdi", DbType="NVarChar(50)")]
		public string cariGrupAdi
		{
			get
			{
				return this._cariGrupAdi;
			}
			set
			{
				if ((this._cariGrupAdi != value))
				{
					this.OncariGrupAdiChanging(value);
					this.SendPropertyChanging();
					this._cariGrupAdi = value;
					this.SendPropertyChanged("cariGrupAdi");
					this.OncariGrupAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cariGrupKodu", DbType="NVarChar(50)")]
		public string cariGrupKodu
		{
			get
			{
				return this._cariGrupKodu;
			}
			set
			{
				if ((this._cariGrupKodu != value))
				{
					this.OncariGrupKoduChanging(value);
					this.SendPropertyChanging();
					this._cariGrupKodu = value;
					this.SendPropertyChanged("cariGrupKodu");
					this.OncariGrupKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cariSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> cariSaveDate
		{
			get
			{
				return this._cariSaveDate;
			}
			set
			{
				if ((this._cariSaveDate != value))
				{
					this.OncariSaveDateChanging(value);
					this.SendPropertyChanging();
					this._cariSaveDate = value;
					this.SendPropertyChanged("cariSaveDate");
					this.OncariSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cariSaveUser", DbType="Int")]
		public System.Nullable<int> cariSaveUser
		{
			get
			{
				return this._cariSaveUser;
			}
			set
			{
				if ((this._cariSaveUser != value))
				{
					this.OncariSaveUserChanging(value);
					this.SendPropertyChanging();
					this._cariSaveUser = value;
					this.SendPropertyChanged("cariSaveUser");
					this.OncariSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cariEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> cariEditDate
		{
			get
			{
				return this._cariEditDate;
			}
			set
			{
				if ((this._cariEditDate != value))
				{
					this.OncariEditDateChanging(value);
					this.SendPropertyChanging();
					this._cariEditDate = value;
					this.SendPropertyChanged("cariEditDate");
					this.OncariEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cariEditUser", DbType="Int")]
		public System.Nullable<int> cariEditUser
		{
			get
			{
				return this._cariEditUser;
			}
			set
			{
				if ((this._cariEditUser != value))
				{
					this.OncariEditUserChanging(value);
					this.SendPropertyChanging();
					this._cariEditUser = value;
					this.SendPropertyChanged("cariEditUser");
					this.OncariEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CARILER")]
	public partial class CARILER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CariKodu;
		
		private string _CariAdi;
		
		private string _VergiDairesi;
		
		private string _VergiNo;
		
		private System.Nullable<int> _GrupID;
		
		private string _Ulke;
		
		private string _Sehir;
		
		private string _Ilce;
		
		private string _Adres;
		
		private string _Telefon1;
		
		private string _Telefon2;
		
		private string _Fax1;
		
		private string _Fax2;
		
		private string _WebAdres;
		
		private string _MailInfo;
		
		private string _Yetkili1;
		
		private string _YetkiliEmail1;
		
		private string _Yetkili2;
		
		private string _YetkiliEmail2;
		
		private System.Nullable<System.DateTime> _SaveDate;
		
		private System.Nullable<int> _SaveUser;
		
		private System.Nullable<System.DateTime> _EditDate;
		
		private System.Nullable<int> _EditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCariKoduChanging(string value);
    partial void OnCariKoduChanged();
    partial void OnCariAdiChanging(string value);
    partial void OnCariAdiChanged();
    partial void OnVergiDairesiChanging(string value);
    partial void OnVergiDairesiChanged();
    partial void OnVergiNoChanging(string value);
    partial void OnVergiNoChanged();
    partial void OnGrupIDChanging(System.Nullable<int> value);
    partial void OnGrupIDChanged();
    partial void OnUlkeChanging(string value);
    partial void OnUlkeChanged();
    partial void OnSehirChanging(string value);
    partial void OnSehirChanged();
    partial void OnIlceChanging(string value);
    partial void OnIlceChanged();
    partial void OnAdresChanging(string value);
    partial void OnAdresChanged();
    partial void OnTelefon1Changing(string value);
    partial void OnTelefon1Changed();
    partial void OnTelefon2Changing(string value);
    partial void OnTelefon2Changed();
    partial void OnFax1Changing(string value);
    partial void OnFax1Changed();
    partial void OnFax2Changing(string value);
    partial void OnFax2Changed();
    partial void OnWebAdresChanging(string value);
    partial void OnWebAdresChanged();
    partial void OnMailInfoChanging(string value);
    partial void OnMailInfoChanged();
    partial void OnYetkili1Changing(string value);
    partial void OnYetkili1Changed();
    partial void OnYetkiliEmail1Changing(string value);
    partial void OnYetkiliEmail1Changed();
    partial void OnYetkili2Changing(string value);
    partial void OnYetkili2Changed();
    partial void OnYetkiliEmail2Changing(string value);
    partial void OnYetkiliEmail2Changed();
    partial void OnSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaveDateChanged();
    partial void OnSaveUserChanging(System.Nullable<int> value);
    partial void OnSaveUserChanged();
    partial void OnEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditDateChanged();
    partial void OnEditUserChanging(System.Nullable<int> value);
    partial void OnEditUserChanged();
    #endregion
		
		public CARILER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariKodu", DbType="NVarChar(50)")]
		public string CariKodu
		{
			get
			{
				return this._CariKodu;
			}
			set
			{
				if ((this._CariKodu != value))
				{
					this.OnCariKoduChanging(value);
					this.SendPropertyChanging();
					this._CariKodu = value;
					this.SendPropertyChanged("CariKodu");
					this.OnCariKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CariAdi", DbType="NVarChar(50)")]
		public string CariAdi
		{
			get
			{
				return this._CariAdi;
			}
			set
			{
				if ((this._CariAdi != value))
				{
					this.OnCariAdiChanging(value);
					this.SendPropertyChanging();
					this._CariAdi = value;
					this.SendPropertyChanged("CariAdi");
					this.OnCariAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiDairesi", DbType="NVarChar(50)")]
		public string VergiDairesi
		{
			get
			{
				return this._VergiDairesi;
			}
			set
			{
				if ((this._VergiDairesi != value))
				{
					this.OnVergiDairesiChanging(value);
					this.SendPropertyChanging();
					this._VergiDairesi = value;
					this.SendPropertyChanged("VergiDairesi");
					this.OnVergiDairesiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VergiNo", DbType="NVarChar(50)")]
		public string VergiNo
		{
			get
			{
				return this._VergiNo;
			}
			set
			{
				if ((this._VergiNo != value))
				{
					this.OnVergiNoChanging(value);
					this.SendPropertyChanging();
					this._VergiNo = value;
					this.SendPropertyChanged("VergiNo");
					this.OnVergiNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupID", DbType="Int")]
		public System.Nullable<int> GrupID
		{
			get
			{
				return this._GrupID;
			}
			set
			{
				if ((this._GrupID != value))
				{
					this.OnGrupIDChanging(value);
					this.SendPropertyChanging();
					this._GrupID = value;
					this.SendPropertyChanged("GrupID");
					this.OnGrupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ulke", DbType="NVarChar(50)")]
		public string Ulke
		{
			get
			{
				return this._Ulke;
			}
			set
			{
				if ((this._Ulke != value))
				{
					this.OnUlkeChanging(value);
					this.SendPropertyChanging();
					this._Ulke = value;
					this.SendPropertyChanged("Ulke");
					this.OnUlkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sehir", DbType="NVarChar(50)")]
		public string Sehir
		{
			get
			{
				return this._Sehir;
			}
			set
			{
				if ((this._Sehir != value))
				{
					this.OnSehirChanging(value);
					this.SendPropertyChanging();
					this._Sehir = value;
					this.SendPropertyChanged("Sehir");
					this.OnSehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ilce", DbType="NVarChar(50)")]
		public string Ilce
		{
			get
			{
				return this._Ilce;
			}
			set
			{
				if ((this._Ilce != value))
				{
					this.OnIlceChanging(value);
					this.SendPropertyChanging();
					this._Ilce = value;
					this.SendPropertyChanged("Ilce");
					this.OnIlceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Adres", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Adres
		{
			get
			{
				return this._Adres;
			}
			set
			{
				if ((this._Adres != value))
				{
					this.OnAdresChanging(value);
					this.SendPropertyChanging();
					this._Adres = value;
					this.SendPropertyChanged("Adres");
					this.OnAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon1", DbType="NVarChar(50)")]
		public string Telefon1
		{
			get
			{
				return this._Telefon1;
			}
			set
			{
				if ((this._Telefon1 != value))
				{
					this.OnTelefon1Changing(value);
					this.SendPropertyChanging();
					this._Telefon1 = value;
					this.SendPropertyChanged("Telefon1");
					this.OnTelefon1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon2", DbType="NVarChar(50)")]
		public string Telefon2
		{
			get
			{
				return this._Telefon2;
			}
			set
			{
				if ((this._Telefon2 != value))
				{
					this.OnTelefon2Changing(value);
					this.SendPropertyChanging();
					this._Telefon2 = value;
					this.SendPropertyChanged("Telefon2");
					this.OnTelefon2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax1", DbType="NVarChar(20)")]
		public string Fax1
		{
			get
			{
				return this._Fax1;
			}
			set
			{
				if ((this._Fax1 != value))
				{
					this.OnFax1Changing(value);
					this.SendPropertyChanging();
					this._Fax1 = value;
					this.SendPropertyChanged("Fax1");
					this.OnFax1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax2", DbType="NVarChar(20)")]
		public string Fax2
		{
			get
			{
				return this._Fax2;
			}
			set
			{
				if ((this._Fax2 != value))
				{
					this.OnFax2Changing(value);
					this.SendPropertyChanging();
					this._Fax2 = value;
					this.SendPropertyChanged("Fax2");
					this.OnFax2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WebAdres", DbType="NVarChar(150)")]
		public string WebAdres
		{
			get
			{
				return this._WebAdres;
			}
			set
			{
				if ((this._WebAdres != value))
				{
					this.OnWebAdresChanging(value);
					this.SendPropertyChanging();
					this._WebAdres = value;
					this.SendPropertyChanged("WebAdres");
					this.OnWebAdresChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MailInfo", DbType="NVarChar(250)")]
		public string MailInfo
		{
			get
			{
				return this._MailInfo;
			}
			set
			{
				if ((this._MailInfo != value))
				{
					this.OnMailInfoChanging(value);
					this.SendPropertyChanging();
					this._MailInfo = value;
					this.SendPropertyChanged("MailInfo");
					this.OnMailInfoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yetkili1", DbType="NVarChar(50)")]
		public string Yetkili1
		{
			get
			{
				return this._Yetkili1;
			}
			set
			{
				if ((this._Yetkili1 != value))
				{
					this.OnYetkili1Changing(value);
					this.SendPropertyChanging();
					this._Yetkili1 = value;
					this.SendPropertyChanged("Yetkili1");
					this.OnYetkili1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetkiliEmail1", DbType="NVarChar(250)")]
		public string YetkiliEmail1
		{
			get
			{
				return this._YetkiliEmail1;
			}
			set
			{
				if ((this._YetkiliEmail1 != value))
				{
					this.OnYetkiliEmail1Changing(value);
					this.SendPropertyChanging();
					this._YetkiliEmail1 = value;
					this.SendPropertyChanged("YetkiliEmail1");
					this.OnYetkiliEmail1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yetkili2", DbType="NVarChar(50)")]
		public string Yetkili2
		{
			get
			{
				return this._Yetkili2;
			}
			set
			{
				if ((this._Yetkili2 != value))
				{
					this.OnYetkili2Changing(value);
					this.SendPropertyChanging();
					this._Yetkili2 = value;
					this.SendPropertyChanged("Yetkili2");
					this.OnYetkili2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YetkiliEmail2", DbType="NVarChar(250)")]
		public string YetkiliEmail2
		{
			get
			{
				return this._YetkiliEmail2;
			}
			set
			{
				if ((this._YetkiliEmail2 != value))
				{
					this.OnYetkiliEmail2Changing(value);
					this.SendPropertyChanging();
					this._YetkiliEmail2 = value;
					this.SendPropertyChanged("YetkiliEmail2");
					this.OnYetkiliEmail2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> SaveDate
		{
			get
			{
				return this._SaveDate;
			}
			set
			{
				if ((this._SaveDate != value))
				{
					this.OnSaveDateChanging(value);
					this.SendPropertyChanging();
					this._SaveDate = value;
					this.SendPropertyChanged("SaveDate");
					this.OnSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaveUser", DbType="Int")]
		public System.Nullable<int> SaveUser
		{
			get
			{
				return this._SaveUser;
			}
			set
			{
				if ((this._SaveUser != value))
				{
					this.OnSaveUserChanging(value);
					this.SendPropertyChanging();
					this._SaveUser = value;
					this.SendPropertyChanged("SaveUser");
					this.OnSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditDate
		{
			get
			{
				return this._EditDate;
			}
			set
			{
				if ((this._EditDate != value))
				{
					this.OnEditDateChanging(value);
					this.SendPropertyChanging();
					this._EditDate = value;
					this.SendPropertyChanged("EditDate");
					this.OnEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditUser", DbType="Int")]
		public System.Nullable<int> EditUser
		{
			get
			{
				return this._EditUser;
			}
			set
			{
				if ((this._EditUser != value))
				{
					this.OnEditUserChanging(value);
					this.SendPropertyChanging();
					this._EditUser = value;
					this.SendPropertyChanged("EditUser");
					this.OnEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STOKGRUPLARI")]
	public partial class STOKGRUPLARI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _grupID;
		
		private string _grupAdi;
		
		private string _grupKodu;
		
		private System.Nullable<int> _grupSaveUser;
		
		private System.Nullable<System.DateTime> _grupSaveDate;
		
		private System.Nullable<int> _grupEditUser;
		
		private System.Nullable<System.DateTime> _grupEditDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngrupIDChanging(int value);
    partial void OngrupIDChanged();
    partial void OngrupAdiChanging(string value);
    partial void OngrupAdiChanged();
    partial void OngrupKoduChanging(string value);
    partial void OngrupKoduChanged();
    partial void OngrupSaveUserChanging(System.Nullable<int> value);
    partial void OngrupSaveUserChanged();
    partial void OngrupSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OngrupSaveDateChanged();
    partial void OngrupEditUserChanging(System.Nullable<int> value);
    partial void OngrupEditUserChanged();
    partial void OngrupEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OngrupEditDateChanged();
    #endregion
		
		public STOKGRUPLARI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int grupID
		{
			get
			{
				return this._grupID;
			}
			set
			{
				if ((this._grupID != value))
				{
					this.OngrupIDChanging(value);
					this.SendPropertyChanging();
					this._grupID = value;
					this.SendPropertyChanged("grupID");
					this.OngrupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupAdi", DbType="NVarChar(50)")]
		public string grupAdi
		{
			get
			{
				return this._grupAdi;
			}
			set
			{
				if ((this._grupAdi != value))
				{
					this.OngrupAdiChanging(value);
					this.SendPropertyChanging();
					this._grupAdi = value;
					this.SendPropertyChanged("grupAdi");
					this.OngrupAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupKodu", DbType="NVarChar(50)")]
		public string grupKodu
		{
			get
			{
				return this._grupKodu;
			}
			set
			{
				if ((this._grupKodu != value))
				{
					this.OngrupKoduChanging(value);
					this.SendPropertyChanging();
					this._grupKodu = value;
					this.SendPropertyChanged("grupKodu");
					this.OngrupKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupSaveUser", DbType="Int")]
		public System.Nullable<int> grupSaveUser
		{
			get
			{
				return this._grupSaveUser;
			}
			set
			{
				if ((this._grupSaveUser != value))
				{
					this.OngrupSaveUserChanging(value);
					this.SendPropertyChanging();
					this._grupSaveUser = value;
					this.SendPropertyChanged("grupSaveUser");
					this.OngrupSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> grupSaveDate
		{
			get
			{
				return this._grupSaveDate;
			}
			set
			{
				if ((this._grupSaveDate != value))
				{
					this.OngrupSaveDateChanging(value);
					this.SendPropertyChanging();
					this._grupSaveDate = value;
					this.SendPropertyChanged("grupSaveDate");
					this.OngrupSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupEditUser", DbType="Int")]
		public System.Nullable<int> grupEditUser
		{
			get
			{
				return this._grupEditUser;
			}
			set
			{
				if ((this._grupEditUser != value))
				{
					this.OngrupEditUserChanging(value);
					this.SendPropertyChanging();
					this._grupEditUser = value;
					this.SendPropertyChanged("grupEditUser");
					this.OngrupEditUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grupEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> grupEditDate
		{
			get
			{
				return this._grupEditDate;
			}
			set
			{
				if ((this._grupEditDate != value))
				{
					this.OngrupEditDateChanging(value);
					this.SendPropertyChanging();
					this._grupEditDate = value;
					this.SendPropertyChanged("grupEditDate");
					this.OngrupEditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STOKLAR")]
	public partial class STOKLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _stokID;
		
		private string _stokBarkod;
		
		private string _stokKodu;
		
		private string _stokAdi;
		
		private string _stokBirim;
		
		private System.Nullable<decimal> _stokAlisfiyat;
		
		private System.Nullable<decimal> _stokSatisfiyat;
		
		private System.Nullable<decimal> _stokAlisKDV;
		
		private System.Nullable<decimal> _stokSatisKDV;
		
		private System.Nullable<int> _stokGrupID;
		
		private System.Data.Linq.Binary _stokResim;
		
		private System.Nullable<int> _stokSaveuser;
		
		private System.Nullable<System.DateTime> _stokSavedate;
		
		private System.Nullable<int> _stokEdituser;
		
		private System.Nullable<System.DateTime> _stokEdittime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstokIDChanging(int value);
    partial void OnstokIDChanged();
    partial void OnstokBarkodChanging(string value);
    partial void OnstokBarkodChanged();
    partial void OnstokKoduChanging(string value);
    partial void OnstokKoduChanged();
    partial void OnstokAdiChanging(string value);
    partial void OnstokAdiChanged();
    partial void OnstokBirimChanging(string value);
    partial void OnstokBirimChanged();
    partial void OnstokAlisfiyatChanging(System.Nullable<decimal> value);
    partial void OnstokAlisfiyatChanged();
    partial void OnstokSatisfiyatChanging(System.Nullable<decimal> value);
    partial void OnstokSatisfiyatChanged();
    partial void OnstokAlisKDVChanging(System.Nullable<decimal> value);
    partial void OnstokAlisKDVChanged();
    partial void OnstokSatisKDVChanging(System.Nullable<decimal> value);
    partial void OnstokSatisKDVChanged();
    partial void OnstokGrupIDChanging(System.Nullable<int> value);
    partial void OnstokGrupIDChanged();
    partial void OnstokResimChanging(System.Data.Linq.Binary value);
    partial void OnstokResimChanged();
    partial void OnstokSaveuserChanging(System.Nullable<int> value);
    partial void OnstokSaveuserChanged();
    partial void OnstokSavedateChanging(System.Nullable<System.DateTime> value);
    partial void OnstokSavedateChanged();
    partial void OnstokEdituserChanging(System.Nullable<int> value);
    partial void OnstokEdituserChanged();
    partial void OnstokEdittimeChanging(System.Nullable<System.DateTime> value);
    partial void OnstokEdittimeChanged();
    #endregion
		
		public STOKLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int stokID
		{
			get
			{
				return this._stokID;
			}
			set
			{
				if ((this._stokID != value))
				{
					this.OnstokIDChanging(value);
					this.SendPropertyChanging();
					this._stokID = value;
					this.SendPropertyChanged("stokID");
					this.OnstokIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokBarkod", DbType="NVarChar(50)")]
		public string stokBarkod
		{
			get
			{
				return this._stokBarkod;
			}
			set
			{
				if ((this._stokBarkod != value))
				{
					this.OnstokBarkodChanging(value);
					this.SendPropertyChanging();
					this._stokBarkod = value;
					this.SendPropertyChanged("stokBarkod");
					this.OnstokBarkodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokKodu", DbType="NVarChar(50)")]
		public string stokKodu
		{
			get
			{
				return this._stokKodu;
			}
			set
			{
				if ((this._stokKodu != value))
				{
					this.OnstokKoduChanging(value);
					this.SendPropertyChanging();
					this._stokKodu = value;
					this.SendPropertyChanged("stokKodu");
					this.OnstokKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokAdi", DbType="NVarChar(50)")]
		public string stokAdi
		{
			get
			{
				return this._stokAdi;
			}
			set
			{
				if ((this._stokAdi != value))
				{
					this.OnstokAdiChanging(value);
					this.SendPropertyChanging();
					this._stokAdi = value;
					this.SendPropertyChanged("stokAdi");
					this.OnstokAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokBirim", DbType="NChar(15)")]
		public string stokBirim
		{
			get
			{
				return this._stokBirim;
			}
			set
			{
				if ((this._stokBirim != value))
				{
					this.OnstokBirimChanging(value);
					this.SendPropertyChanging();
					this._stokBirim = value;
					this.SendPropertyChanged("stokBirim");
					this.OnstokBirimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokAlisfiyat", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> stokAlisfiyat
		{
			get
			{
				return this._stokAlisfiyat;
			}
			set
			{
				if ((this._stokAlisfiyat != value))
				{
					this.OnstokAlisfiyatChanging(value);
					this.SendPropertyChanging();
					this._stokAlisfiyat = value;
					this.SendPropertyChanged("stokAlisfiyat");
					this.OnstokAlisfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokSatisfiyat", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> stokSatisfiyat
		{
			get
			{
				return this._stokSatisfiyat;
			}
			set
			{
				if ((this._stokSatisfiyat != value))
				{
					this.OnstokSatisfiyatChanging(value);
					this.SendPropertyChanging();
					this._stokSatisfiyat = value;
					this.SendPropertyChanged("stokSatisfiyat");
					this.OnstokSatisfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokAlisKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> stokAlisKDV
		{
			get
			{
				return this._stokAlisKDV;
			}
			set
			{
				if ((this._stokAlisKDV != value))
				{
					this.OnstokAlisKDVChanging(value);
					this.SendPropertyChanging();
					this._stokAlisKDV = value;
					this.SendPropertyChanged("stokAlisKDV");
					this.OnstokAlisKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokSatisKDV", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> stokSatisKDV
		{
			get
			{
				return this._stokSatisKDV;
			}
			set
			{
				if ((this._stokSatisKDV != value))
				{
					this.OnstokSatisKDVChanging(value);
					this.SendPropertyChanging();
					this._stokSatisKDV = value;
					this.SendPropertyChanged("stokSatisKDV");
					this.OnstokSatisKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokGrupID", DbType="Int")]
		public System.Nullable<int> stokGrupID
		{
			get
			{
				return this._stokGrupID;
			}
			set
			{
				if ((this._stokGrupID != value))
				{
					this.OnstokGrupIDChanging(value);
					this.SendPropertyChanging();
					this._stokGrupID = value;
					this.SendPropertyChanged("stokGrupID");
					this.OnstokGrupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokResim", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary stokResim
		{
			get
			{
				return this._stokResim;
			}
			set
			{
				if ((this._stokResim != value))
				{
					this.OnstokResimChanging(value);
					this.SendPropertyChanging();
					this._stokResim = value;
					this.SendPropertyChanged("stokResim");
					this.OnstokResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokSaveuser", DbType="Int")]
		public System.Nullable<int> stokSaveuser
		{
			get
			{
				return this._stokSaveuser;
			}
			set
			{
				if ((this._stokSaveuser != value))
				{
					this.OnstokSaveuserChanging(value);
					this.SendPropertyChanging();
					this._stokSaveuser = value;
					this.SendPropertyChanged("stokSaveuser");
					this.OnstokSaveuserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokSavedate", DbType="DateTime")]
		public System.Nullable<System.DateTime> stokSavedate
		{
			get
			{
				return this._stokSavedate;
			}
			set
			{
				if ((this._stokSavedate != value))
				{
					this.OnstokSavedateChanging(value);
					this.SendPropertyChanging();
					this._stokSavedate = value;
					this.SendPropertyChanged("stokSavedate");
					this.OnstokSavedateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokEdituser", DbType="Int")]
		public System.Nullable<int> stokEdituser
		{
			get
			{
				return this._stokEdituser;
			}
			set
			{
				if ((this._stokEdituser != value))
				{
					this.OnstokEdituserChanging(value);
					this.SendPropertyChanging();
					this._stokEdituser = value;
					this.SendPropertyChanged("stokEdituser");
					this.OnstokEdituserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokEdittime", DbType="DateTime")]
		public System.Nullable<System.DateTime> stokEdittime
		{
			get
			{
				return this._stokEdittime;
			}
			set
			{
				if ((this._stokEdittime != value))
				{
					this.OnstokEdittimeChanging(value);
					this.SendPropertyChanging();
					this._stokEdittime = value;
					this.SendPropertyChanged("stokEdittime");
					this.OnstokEdittimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KASAHAREKETLERI")]
	public partial class KASAHAREKETLERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _kasaID;
		
		private System.Nullable<int> _cariID;
		
		private System.Nullable<System.DateTime> _tarih;
		
		private string _evrakTuru;
		
		private System.Nullable<int> _evrakID;
		
		private string _gcKodu;
		
		private System.Nullable<decimal> _tutar;
		
		private string _belgeNo;
		
		private string _aciklama;
		
		private System.Nullable<System.DateTime> _saveDate;
		
		private System.Nullable<int> _saveUser;
		
		private System.Nullable<System.DateTime> _editDate;
		
		private System.Nullable<int> _editUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnkasaIDChanging(System.Nullable<int> value);
    partial void OnkasaIDChanged();
    partial void OncariIDChanging(System.Nullable<int> value);
    partial void OncariIDChanged();
    partial void OntarihChanging(System.Nullable<System.DateTime> value);
    partial void OntarihChanged();
    partial void OnevrakTuruChanging(string value);
    partial void OnevrakTuruChanged();
    partial void OnevrakIDChanging(System.Nullable<int> value);
    partial void OnevrakIDChanged();
    partial void OngcKoduChanging(string value);
    partial void OngcKoduChanged();
    partial void OntutarChanging(System.Nullable<decimal> value);
    partial void OntutarChanged();
    partial void OnbelgeNoChanging(string value);
    partial void OnbelgeNoChanged();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    partial void OnsaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnsaveDateChanged();
    partial void OnsaveUserChanging(System.Nullable<int> value);
    partial void OnsaveUserChanged();
    partial void OneditDateChanging(System.Nullable<System.DateTime> value);
    partial void OneditDateChanged();
    partial void OneditUserChanging(System.Nullable<int> value);
    partial void OneditUserChanged();
    #endregion
		
		public KASAHAREKETLERI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kasaID", DbType="Int")]
		public System.Nullable<int> kasaID
		{
			get
			{
				return this._kasaID;
			}
			set
			{
				if ((this._kasaID != value))
				{
					this.OnkasaIDChanging(value);
					this.SendPropertyChanging();
					this._kasaID = value;
					this.SendPropertyChanged("kasaID");
					this.OnkasaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cariID", DbType="Int")]
		public System.Nullable<int> cariID
		{
			get
			{
				return this._cariID;
			}
			set
			{
				if ((this._cariID != value))
				{
					this.OncariIDChanging(value);
					this.SendPropertyChanging();
					this._cariID = value;
					this.SendPropertyChanged("cariID");
					this.OncariIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> tarih
		{
			get
			{
				return this._tarih;
			}
			set
			{
				if ((this._tarih != value))
				{
					this.OntarihChanging(value);
					this.SendPropertyChanging();
					this._tarih = value;
					this.SendPropertyChanged("tarih");
					this.OntarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evrakTuru", DbType="NVarChar(50)")]
		public string evrakTuru
		{
			get
			{
				return this._evrakTuru;
			}
			set
			{
				if ((this._evrakTuru != value))
				{
					this.OnevrakTuruChanging(value);
					this.SendPropertyChanging();
					this._evrakTuru = value;
					this.SendPropertyChanged("evrakTuru");
					this.OnevrakTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evrakID", DbType="Int")]
		public System.Nullable<int> evrakID
		{
			get
			{
				return this._evrakID;
			}
			set
			{
				if ((this._evrakID != value))
				{
					this.OnevrakIDChanging(value);
					this.SendPropertyChanging();
					this._evrakID = value;
					this.SendPropertyChanged("evrakID");
					this.OnevrakIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gcKodu", DbType="NVarChar(5)")]
		public string gcKodu
		{
			get
			{
				return this._gcKodu;
			}
			set
			{
				if ((this._gcKodu != value))
				{
					this.OngcKoduChanging(value);
					this.SendPropertyChanging();
					this._gcKodu = value;
					this.SendPropertyChanged("gcKodu");
					this.OngcKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tutar", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> tutar
		{
			get
			{
				return this._tutar;
			}
			set
			{
				if ((this._tutar != value))
				{
					this.OntutarChanging(value);
					this.SendPropertyChanging();
					this._tutar = value;
					this.SendPropertyChanged("tutar");
					this.OntutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_belgeNo", DbType="NVarChar(50)")]
		public string belgeNo
		{
			get
			{
				return this._belgeNo;
			}
			set
			{
				if ((this._belgeNo != value))
				{
					this.OnbelgeNoChanging(value);
					this.SendPropertyChanging();
					this._belgeNo = value;
					this.SendPropertyChanged("belgeNo");
					this.OnbelgeNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this.OnaciklamaChanging(value);
					this.SendPropertyChanging();
					this._aciklama = value;
					this.SendPropertyChanged("aciklama");
					this.OnaciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> saveDate
		{
			get
			{
				return this._saveDate;
			}
			set
			{
				if ((this._saveDate != value))
				{
					this.OnsaveDateChanging(value);
					this.SendPropertyChanging();
					this._saveDate = value;
					this.SendPropertyChanged("saveDate");
					this.OnsaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saveUser", DbType="Int")]
		public System.Nullable<int> saveUser
		{
			get
			{
				return this._saveUser;
			}
			set
			{
				if ((this._saveUser != value))
				{
					this.OnsaveUserChanging(value);
					this.SendPropertyChanging();
					this._saveUser = value;
					this.SendPropertyChanged("saveUser");
					this.OnsaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> editDate
		{
			get
			{
				return this._editDate;
			}
			set
			{
				if ((this._editDate != value))
				{
					this.OneditDateChanging(value);
					this.SendPropertyChanging();
					this._editDate = value;
					this.SendPropertyChanged("editDate");
					this.OneditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editUser", DbType="Int")]
		public System.Nullable<int> editUser
		{
			get
			{
				return this._editUser;
			}
			set
			{
				if ((this._editUser != value))
				{
					this.OneditUserChanging(value);
					this.SendPropertyChanging();
					this._editUser = value;
					this.SendPropertyChanged("editUser");
					this.OneditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KASALAR")]
	public partial class KASALAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kasaID;
		
		private string _kasaKodu;
		
		private string _kasaAdi;
		
		private string _kasaAciklama;
		
		private System.Nullable<System.DateTime> _kasaSaveDate;
		
		private System.Nullable<int> _kasaSaveUser;
		
		private System.Nullable<System.DateTime> _kasaEditDate;
		
		private System.Nullable<int> _kasaEditUser;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkasaIDChanging(int value);
    partial void OnkasaIDChanged();
    partial void OnkasaKoduChanging(string value);
    partial void OnkasaKoduChanged();
    partial void OnkasaAdiChanging(string value);
    partial void OnkasaAdiChanged();
    partial void OnkasaAciklamaChanging(string value);
    partial void OnkasaAciklamaChanged();
    partial void OnkasaSaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnkasaSaveDateChanged();
    partial void OnkasaSaveUserChanging(System.Nullable<int> value);
    partial void OnkasaSaveUserChanged();
    partial void OnkasaEditDateChanging(System.Nullable<System.DateTime> value);
    partial void OnkasaEditDateChanged();
    partial void OnkasaEditUserChanging(System.Nullable<int> value);
    partial void OnkasaEditUserChanged();
    #endregion
		
		public KASALAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kasaID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kasaID
		{
			get
			{
				return this._kasaID;
			}
			set
			{
				if ((this._kasaID != value))
				{
					this.OnkasaIDChanging(value);
					this.SendPropertyChanging();
					this._kasaID = value;
					this.SendPropertyChanged("kasaID");
					this.OnkasaIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kasaKodu", DbType="NVarChar(50)")]
		public string kasaKodu
		{
			get
			{
				return this._kasaKodu;
			}
			set
			{
				if ((this._kasaKodu != value))
				{
					this.OnkasaKoduChanging(value);
					this.SendPropertyChanging();
					this._kasaKodu = value;
					this.SendPropertyChanged("kasaKodu");
					this.OnkasaKoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kasaAdi", DbType="NVarChar(50)")]
		public string kasaAdi
		{
			get
			{
				return this._kasaAdi;
			}
			set
			{
				if ((this._kasaAdi != value))
				{
					this.OnkasaAdiChanging(value);
					this.SendPropertyChanging();
					this._kasaAdi = value;
					this.SendPropertyChanged("kasaAdi");
					this.OnkasaAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kasaAciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string kasaAciklama
		{
			get
			{
				return this._kasaAciklama;
			}
			set
			{
				if ((this._kasaAciklama != value))
				{
					this.OnkasaAciklamaChanging(value);
					this.SendPropertyChanging();
					this._kasaAciklama = value;
					this.SendPropertyChanged("kasaAciklama");
					this.OnkasaAciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kasaSaveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> kasaSaveDate
		{
			get
			{
				return this._kasaSaveDate;
			}
			set
			{
				if ((this._kasaSaveDate != value))
				{
					this.OnkasaSaveDateChanging(value);
					this.SendPropertyChanging();
					this._kasaSaveDate = value;
					this.SendPropertyChanged("kasaSaveDate");
					this.OnkasaSaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kasaSaveUser", DbType="Int")]
		public System.Nullable<int> kasaSaveUser
		{
			get
			{
				return this._kasaSaveUser;
			}
			set
			{
				if ((this._kasaSaveUser != value))
				{
					this.OnkasaSaveUserChanging(value);
					this.SendPropertyChanging();
					this._kasaSaveUser = value;
					this.SendPropertyChanged("kasaSaveUser");
					this.OnkasaSaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kasaEditDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> kasaEditDate
		{
			get
			{
				return this._kasaEditDate;
			}
			set
			{
				if ((this._kasaEditDate != value))
				{
					this.OnkasaEditDateChanging(value);
					this.SendPropertyChanging();
					this._kasaEditDate = value;
					this.SendPropertyChanged("kasaEditDate");
					this.OnkasaEditDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kasaEditUser", DbType="Int")]
		public System.Nullable<int> kasaEditUser
		{
			get
			{
				return this._kasaEditUser;
			}
			set
			{
				if ((this._kasaEditUser != value))
				{
					this.OnkasaEditUserChanging(value);
					this.SendPropertyChanging();
					this._kasaEditUser = value;
					this.SendPropertyChanged("kasaEditUser");
					this.OnkasaEditUserChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CARIHAREKETLERI")]
	public partial class CARIHAREKETLERI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _cariID;
		
		private string _evrakTuru;
		
		private System.Nullable<int> _evrakID;
		
		private System.Nullable<decimal> _borc;
		
		private System.Nullable<decimal> _alacak;
		
		private string _aciklama;
		
		private System.Nullable<System.DateTime> _tarih;
		
		private string _tipi;
		
		private System.Nullable<System.DateTime> _saveDate;
		
		private System.Nullable<int> _saveUser;
		
		private System.Nullable<System.DateTime> _editDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OncariIDChanging(System.Nullable<int> value);
    partial void OncariIDChanged();
    partial void OnevrakTuruChanging(string value);
    partial void OnevrakTuruChanged();
    partial void OnevrakIDChanging(System.Nullable<int> value);
    partial void OnevrakIDChanged();
    partial void OnborcChanging(System.Nullable<decimal> value);
    partial void OnborcChanged();
    partial void OnalacakChanging(System.Nullable<decimal> value);
    partial void OnalacakChanged();
    partial void OnaciklamaChanging(string value);
    partial void OnaciklamaChanged();
    partial void OntarihChanging(System.Nullable<System.DateTime> value);
    partial void OntarihChanged();
    partial void OntipiChanging(string value);
    partial void OntipiChanged();
    partial void OnsaveDateChanging(System.Nullable<System.DateTime> value);
    partial void OnsaveDateChanged();
    partial void OnsaveUserChanging(System.Nullable<int> value);
    partial void OnsaveUserChanged();
    partial void OneditDateChanging(System.Nullable<System.DateTime> value);
    partial void OneditDateChanged();
    #endregion
		
		public CARIHAREKETLERI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cariID", DbType="Int")]
		public System.Nullable<int> cariID
		{
			get
			{
				return this._cariID;
			}
			set
			{
				if ((this._cariID != value))
				{
					this.OncariIDChanging(value);
					this.SendPropertyChanging();
					this._cariID = value;
					this.SendPropertyChanged("cariID");
					this.OncariIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evrakTuru", DbType="NVarChar(50)")]
		public string evrakTuru
		{
			get
			{
				return this._evrakTuru;
			}
			set
			{
				if ((this._evrakTuru != value))
				{
					this.OnevrakTuruChanging(value);
					this.SendPropertyChanging();
					this._evrakTuru = value;
					this.SendPropertyChanged("evrakTuru");
					this.OnevrakTuruChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_evrakID", DbType="Int")]
		public System.Nullable<int> evrakID
		{
			get
			{
				return this._evrakID;
			}
			set
			{
				if ((this._evrakID != value))
				{
					this.OnevrakIDChanging(value);
					this.SendPropertyChanging();
					this._evrakID = value;
					this.SendPropertyChanged("evrakID");
					this.OnevrakIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_borc", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> borc
		{
			get
			{
				return this._borc;
			}
			set
			{
				if ((this._borc != value))
				{
					this.OnborcChanging(value);
					this.SendPropertyChanging();
					this._borc = value;
					this.SendPropertyChanged("borc");
					this.OnborcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alacak", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> alacak
		{
			get
			{
				return this._alacak;
			}
			set
			{
				if ((this._alacak != value))
				{
					this.OnalacakChanging(value);
					this.SendPropertyChanging();
					this._alacak = value;
					this.SendPropertyChanged("alacak");
					this.OnalacakChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_aciklama", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string aciklama
		{
			get
			{
				return this._aciklama;
			}
			set
			{
				if ((this._aciklama != value))
				{
					this.OnaciklamaChanging(value);
					this.SendPropertyChanging();
					this._aciklama = value;
					this.SendPropertyChanged("aciklama");
					this.OnaciklamaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> tarih
		{
			get
			{
				return this._tarih;
			}
			set
			{
				if ((this._tarih != value))
				{
					this.OntarihChanging(value);
					this.SendPropertyChanging();
					this._tarih = value;
					this.SendPropertyChanged("tarih");
					this.OntarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipi", DbType="NVarChar(50)")]
		public string tipi
		{
			get
			{
				return this._tipi;
			}
			set
			{
				if ((this._tipi != value))
				{
					this.OntipiChanging(value);
					this.SendPropertyChanging();
					this._tipi = value;
					this.SendPropertyChanged("tipi");
					this.OntipiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saveDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> saveDate
		{
			get
			{
				return this._saveDate;
			}
			set
			{
				if ((this._saveDate != value))
				{
					this.OnsaveDateChanging(value);
					this.SendPropertyChanging();
					this._saveDate = value;
					this.SendPropertyChanged("saveDate");
					this.OnsaveDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_saveUser", DbType="Int")]
		public System.Nullable<int> saveUser
		{
			get
			{
				return this._saveUser;
			}
			set
			{
				if ((this._saveUser != value))
				{
					this.OnsaveUserChanging(value);
					this.SendPropertyChanging();
					this._saveUser = value;
					this.SendPropertyChanged("saveUser");
					this.OnsaveUserChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_editDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> editDate
		{
			get
			{
				return this._editDate;
			}
			set
			{
				if ((this._editDate != value))
				{
					this.OneditDateChanging(value);
					this.SendPropertyChanging();
					this._editDate = value;
					this.SendPropertyChanged("editDate");
					this.OneditDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
